image: $REGISTRY_CI/gitlab-ci-base:buster

stages:
  - build-test
  - test
  - package
  - build
  - deploy

variables:
  GIT_DEPTH: 10

#########################
####  TEMPLATE      ####
########################

.test_template: &test_definition
  stage: test
  tags:
    - gcp-high-load-runner-prod
  allow_failure: false
  variables:
    HIPAY_API_MOTO_USER_TEST: $HIPAY_API_USER_TEST
    HIPAY_API_MOTO_PASSWORD_TEST: $HIPAY_API_PASSWORD_TEST
    HIPAY_MOTO_SECRET_PASSPHRASE_TEST: $HIPAY_SECRET_PASSPHRASE_TEST
    PI_CI_DATA_URL: $PI_CI_DATA_URL
    ADMIN_MAIL: "demo@hipay.com"
    ADMIN_PASSWD: "hipay123"
    PS_ERASE_DB: 1
    PS_INSTALL_DB: 1
    PS_LANGUAGE: "fr"
    PS_COUNTRY: "fr"
    PS_INSTALL_AUTO: 1
    PS_DEV_MODE: 1
    PS_FOLDER_ADMIN: "admin-hipay"
    PS_FOLDER_INSTALL: "installOLD"
    PS_HANDLE_DYNAMIC_DOMAIN: 0
    PS_ALL_LANGUAGES: 0
    DB_SERVER: "database"
    DB_USER: "root"
    DB_PASSWD: "admin"
    MYSQL_HOST: "database"
    MYSQL_ROOT_PASSWORD: "admin"
  services:
    - name: $CI_REGISTRY/test-jobs-${DOCKER_STACK}-${DOCKER_SERVICE}_web17:${CI_COMMIT_REF_SLUG}
      alias: prestashop
    - name: mysql:5.7
      alias: database
  artifacts:
    paths:
      - bin/tests/errors
      - bin/tests/tests-cypress/cypress/videos
      - bin/tests/tests-cypress/cypress/screenshots
    when: always
  except:
    variables:
      - $ACCESS_TOKEN

.build-prestashop:
  stage: build
  rules:
    - if: $ACCESS_TOKEN
      when: on_success
    - when: manual
  image: $REGISTRY_CI/gitlab-ci-base:deployment
  script:
    - docker build -f bin/docker/images/prestashop/Dockerfile${PS_VERSION} . -t ${REGISTRY_CD}/${DOCKER_STACK}-${DOCKER_SERVICE}-web${PS_VERSION}:${CI_COMMIT_REF_SLUG}
    - /tools/auth-as-end-user.sh
    - docker push ${REGISTRY_CD}/${DOCKER_STACK}-${DOCKER_SERVICE}-web${PS_VERSION}:${CI_COMMIT_REF_SLUG}
    - /tools/logout-end-user.sh
  tags:
    - gcp-default-runner-prod

.deploy2recette-prestashop:
  stage: deploy
  rules:
    - if: $ACCESS_TOKEN
      when: on_success
    - when: manual
  image: $REGISTRY_CI/gitlab-ci-base:deployment
  variables:
    GPC_ACCOUNT: ''
    RELEASE_NAME: ${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${PS_VERSION}
  script:
    - echo $RELEASE_NAME
    - /tools/auth-to-cd-cluster.sh
    - >
      helm install $RELEASE_NAME ./bin/docker/kubernetes/helm/
      --set prestashop_image="${REGISTRY_CD}/${DOCKER_STACK}-${DOCKER_SERVICE}-web${PS_VERSION}"
      --set prestashop_tag="${CI_COMMIT_REF_SLUG}"
      --set prestashop_url="${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${PS_VERSION}.${URL_CD}"
      --set ps_version="${PS_FULL_VERSION}"
      --set ps_domain="${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${PS_VERSION}.${URL_CD}"
      --set db_name="prestashop${PS_VERSION}"
      --set hipay_api_user_test="$HIPAY_API_USER_RE7"
      --set hipay_api_password_test="$HIPAY_API_PASSWORD_RE7"
      --set hipay_tokenjs_username_test="$HIPAY_TOKENJS_USERNAME_RE7"
      --set hipay_tokenjs_publickey_test="$HIPAY_TOKENJS_PUBLICKEY_RE7"
      --set hipay_secret_passphrase_test="$HIPAY_SECRET_PASSPHRASE_RE7"
      --set hipay_api_moto_user_test=""
      --set hipay_api_moto_password_test=""
      --set hipay_moto_secret_passphrase_test=""
      --set pi_data_url="$PI_CI_DATA_URL"
    - /tools/logout-end-user.sh
  allow_failure: true
  tags:
    - gcp-default-runner-prod

.stop_review-prestashop:
  stage: deploy
  image: $REGISTRY_CI/gitlab-ci-base:deployment
  variables:
    GIT_STRATEGY: none
    RELEASE_NAME: ${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${PS_VERSION}
  script:
    - /tools/auth-to-cd-cluster.sh
    - helm uninstall $RELEASE_NAME
    - /tools/logout-end-user.sh
  rules:
    - if: $ACCESS_TOKEN
      when: on_success
    - when: manual
  environment:
    name: review-${PS_VERSION}/${CI_COMMIT_REF_SLUG}
    action: stop
  tags:
    - gcp-default-runner-prod

#########################
####  JOBS          ####
########################
build-test-kaniko:
  stage: build-test
  image:
    name: gcr.io/kaniko-project/executor:v1.6.0-debug
  script:
     - /kaniko/executor
            --cache=true
            --context "dir://${CI_PROJECT_DIR}"
            --dockerfile "./bin/docker/images/prestashop/Dockerfile17"
            --destination "$CI_REGISTRY/test-jobs-${DOCKER_STACK}-${DOCKER_SERVICE}_web17:${CI_COMMIT_REF_SLUG}"
  except:
    variables:
      - $ACCESS_TOKEN
  tags:
    - gcp-default-runner-prod

test-casper-17-1:
  <<: *test_definition
  script:
    - sh bin/tests/casper_run_circle.sh 0 ps17 http:\/\/prestashop/
  retry: 2

test-casper-17-2:
  <<: *test_definition
  script:
    - sh bin/tests/casper_run_circle.sh 1 ps17 http:\/\/prestashop/
  retry: 2

test-cypress-17-1:
  <<: *test_definition
  script:
    - cp ./bin/tests/tests-cypress/.npmrc.sample ./bin/tests/tests-cypress/.npmrc
    - cd bin/tests/tests-cypress
    - yarn install
    - bash /tools/run-cypress-test.sh -f $TESTS_FOLDERS_1 -e $EXCLUDED_TEST_FILES --config baseUrl=http:\/\/prestashop/ --env $CYPRESS_ENV
  retry: 2

package:
  stage: package
  before_script:
    - apt-get install -y zip sshpass
  script:
    - echo "Package module $CI_COMMIT_REF_SLUG"
    - cd src/hipay_enterprise
    - composer install --no-dev
    - cd ../..
    - ./package-ready-for-prestashop/builder/module_builder.sh -v $CI_COMMIT_REF_SLUG
  #    - chmod u+x bin/deployment/deploy_package.sh
  #    - ./bin/deployment/deploy_package.sh
  artifacts:
    paths:
      - ./package-ready-for-prestashop
  tags:
    - gcp-default-runner-prod
  except:
    variables:
      - $ACCESS_TOKEN

build-prestashop16:
  variables:
    PS_VERSION: 16
  extends: .build-prestashop

build-prestashop17:
  variables:
    PS_VERSION: 17
  extends: .build-prestashop

deploy2recette-prestashop16:
  variables:
    PS_VERSION: 16
    PS_FULL_VERSION: 1.6.1.16
  extends: .deploy2recette-prestashop
  environment:
    name: review-${PS_VERSION}/${CI_COMMIT_REF_SLUG}
    url: https://${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${PS_VERSION}.${URL_CD}
    on_stop: stop_review-prestashop16

deploy2recette-prestashop17:
  variables:
    PS_VERSION: 17
    PS_FULL_VERSION: 1.7.2.0
  extends: .deploy2recette-prestashop
  environment:
    name: review-${PS_VERSION}/${CI_COMMIT_REF_SLUG}
    url: https://${DOCKER_STACK}-${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${PS_VERSION}.${URL_CD}
    on_stop: stop_review-prestashop17

stop_review-prestashop16:
  variables:
    PS_VERSION: 16
  extends: .stop_review-prestashop

stop_review-prestashop17:
  variables:
    PS_VERSION: 17
  extends: .stop_review-prestashop
