mysql:
  container_name: mysql-hipay-enterprise
  image: mysql:5.6.23
  ports:
    - "3308:3306"
smtp:
  image: schickling/mailcatcher
  container_name: smtp-hipay-enterprise
  ports:
    - "1082:1080"