version: "2.1"

networks:
  prestashop:
    internal: true
  outside:
    external: true

services:
  mysql:
    container_name: mysql-ps17-$CI_JOB_ID-RE
    networks:
      - prestashop
    env_file:
      - ./conf/env_file/stage/env
  prestashop17:
    container_name: hipay-enterprise-ps17-$CI_JOB_ID-RE
    build:
      context: .
      dockerfile: ./conf/docker/Dockerfile17
    env_file:
      - ./conf/env_file/stage/env
      - ./conf/env_file/stage/env17
    networks:
      - prestashop
      - outside
  smtp:
    container_name: smtp-test-$CI_JOB_ID-RE
    networks:
      - prestashop
