version: "3"

networks:
  prestashop:
    internal: true
  outside-overlay:
    external: true

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-ps17-$CI_JOB_ID-RE
    networks:
      - prestashop
    env_file:
      - ./conf/env_file/stage/env
  prestashop17:
    container_name: hipay-enterprise-ps17-$CI_JOB_ID-RE
    image: hipay-enterprise-ps17-$CI_COMMIT_REF_SLUG
    build:
      context: .
      dockerfile: ./conf/docker/Dockerfile17
    env_file:
      - ./conf/env_file/stage/env
      - ./conf/env_file/stage/env17
    networks:
      - prestashop
      - outside-overlay
  smtp:
    image: schickling/mailcatcher
    container_name: smtp-test-$CI_JOB_ID-RE
    networks:
      - prestashop
