version: "2.1"

services:
  mysql:
    container_name: {CONTAINER_NAME_MYSQL}
    ports:
      - "{PORT_MYSQL}:3306"
    env_file:
      - ./conf/env_file/production/env
    labels:
      - "com.hipay.github={label}"
      - "com.hipay.circleci={circleci}"
    mem_limit: 500M
    restart: always
  prestashop16:
    container_name: {CONTAINER_NAME_WEB}
    build:
      context: .
      dockerfile: ./conf/docker/Dockerfile16
    ports:
      - "{PORT_WEB}:80"
    links:
      - smtp
      - mysql
    env_file:
      - ./conf/env_file/production/env
      - ./conf/env_file/production/env16
    labels:
      - "com.hipay.github={label}"
      - "com.hipay.circleci={circleci}"
    mem_limit: 500M
    restart: always
  prestashop17:
    container_name: {CONTAINER_NAME_WEB1}
    build:
      context: .
      dockerfile: ./conf/docker/Dockerfile17
    ports:
      - "{PORT_WEB1}:80"
    links:
      - smtp
      - mysql
    env_file:
      - ./conf/env_file/production/env
      - ./conf/env_file/production/env17
    labels:
      - "com.hipay.github={label}"
      - "com.hipay.circleci={circleci}"
    mem_limit: 500M
    restart: always
  smtp:
    container_name: {CONTAINER_NAME_SMTP}
    ports:
      - "{PORT_SMTP}:1080"
    labels:
    - "com.hipay.github={label}"
    - "com.hipay.circleci={circleci}"
    mem_limit: 256M
    restart: always

