prestashop17:
  container_name: hipay-enterprise-shop-ps17
  dockerfile: ./conf/docker/Dockerfile17
  build: .
  ports:
    - "8087:80"
  links:
    - smtp
    - mysql
  env_file:
    - ./conf/env_file/development/env
    - ./conf/env_file/development/env17
  volumes:
    - ./web17:/var/www/html
    - ./src/hipay_enterprise:/var/www/html/modules/hipay_enterprise
  mem_limit: 500M
