mysql:
  env_file:
    - ./conf/env_file/development/env
  volumes:
    - ./data/:/var/lib/mysql
prestashop17:
  container_name: hipay-enterprise-shop-ps17
  dockerfile: ./conf/docker/Dockerfile17
  build: .
  ports:
    - "8087:80"
  links:
    - smtp
    - mysql
  env_file:
    - ./conf/env_file/env
    - ./conf/env_file/env17
  volumes:
    - ./web17:/var/www/html
    - ./src/hipay_enterprise:/var/www/html/modules/hipay_enterprise
