version: "3.3"

services:
  web:
    container_name: prestashop_web
    image: gcr.io/pi-dev-sandbox/test-jobs-${DOCKER_STACK}-${DOCKER_SERVICE}_web17:${CI_COMMIT_REF_SLUG}
    build:
      context: .
      dockerfile: ./bin/docker/images/prestashop/Dockerfile17
    depends_on:
      - database
    env_file:
      - ./bin/docker/conf/test/env
      - ./bin/docker/conf/test/env17
    ports:
      - "8087:80"
  database:
    image: mysql:5.7
    container_name: prestashop_database
    env_file:
      - ./bin/docker/conf/test/env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3318:3306"

#  smtp:
#    image: schickling/mailcatcher
#    container_name: ${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}_smtp
#    networks:
#      prestashop:
#        aliases:
#          - ${DOCKER_SERVICE}-${CI_COMMIT_REF_SLUG}-${CI_JOB_ID}_smtp
