apiVersion: v1
kind: Service
metadata:
  name: prestashop-service-{{ .Release.Name }}
  namespace: default
  labels:
    cd-hipay: cron-delete
spec:
  ports:
    - port: 80
      protocol: TCP
      name: web
      targetPort: 80
  selector:
    app: prestashop-{{ .Release.Name }}
    tier: frontend-{{ .Release.Name }}
  type: NodePort
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-tls-{{ .Release.Name }}
  namespace: default
  labels:
    cd-hipay: cron-delete
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.prestashop_url  }}`)
      kind: Rule
      priority: 1
      services:
        - name: prestashop-service-{{ .Release.Name }}
          port: 80
      middlewares:
        - name: hipay-ipwhitelist
  tls:
    certResolver: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-{{ .Release.Name }}
  namespace: default
  labels:
    cd-hipay: cron-delete
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.prestashop_url  }}`)
      kind: Rule
      priority: 1
      services:
        - name: prestashop-service-{{ .Release.Name }}
          port: 80
      middlewares:
        - name: hipay-ipwhitelist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop-{{ .Release.Name }}
  labels:
    app: prestashop-{{ .Release.Name }}
    cd-hipay: cron-delete
spec:
  selector:
    matchLabels:
      app: prestashop-{{ .Release.Name }}
      tier: frontend-{{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prestashop-{{ .Release.Name }}
        tier: frontend-{{ .Release.Name }}
        cd-hipay: cron-delete
    spec:
      containers:
      - image: {{ .Values.prestashop_image }}:{{ .Values.prestashop_tag }}
        imagePullPolicy: Always
        name: prestashop-{{ .Release.Name }}
        resources:
          requests:
            memory: "256M"
            cpu: "500m"
          limits:
            memory: "512M"
            cpu: "1000m"
        envFrom:
          - configMapRef:
              name: prestashop-configmap-{{ .Release.Name }}
        ports:
          - containerPort: 80
            name: prestashop
      nodeSelector:
        node_type: default
      tolerations:
        - key: cd_service
          operator: Equal
          value: only
          effect: NoExecute
